CREATE PROC FI_SP_IncBenef
    @NOME          VARCHAR (50),
	@CPF           VARCHAR (11),
	@IDCLIENTE			BIGINT
AS
BEGIN
	INSERT INTO BENEFICIARIOS (CPF, NOME, IDCLIENTE)
	VALUES (@CPF, @NOME, @IDCLIENTE)

	SELECT SCOPE_IDENTITY()
END